config/routes.rb
Bridge::Application.routes.draw do
  root to: "static_pages#home"
    get "static_pages/root"
    post "static_pages/allow_access"
    get "static_pages/not_home"

  namespace :api, defaults: {format: :json} do
    resources :images
    resources :explores, only: [:index]
    resources :users, only: [:show, :create, :update, :destroy]
    resources :tags, only: [:index, :create]
    resources :passion_joins, only: [:create, :destroy]
    resources :skill_joins, only: [:create, :destroy]
    resources :projects, only: [:create, :show, :update, :destroy, :index]
    resources :partnerships, only: [:index]
    resources :pending_requests, only: [:index]
  end
  resource :session, only: [:new, :create, :destroy]
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                 :integer          not null, primary key
#  project_id         :integer
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  created_at         :datetime
#  updated_at         :datetime
#  user_id            :integer
#

class Image < ActiveRecord::Base
  has_attached_file :photo, styles: { :medium => "400x400>", :thumb => "200x200>" }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
  belongs_to :project
  belongs_to :user
end

app/models/partnership.rb
# == Schema Information
#
# Table name: partnerships
#
#  id          :integer          not null, primary key
#  in_partner  :integer
#  out_partner :integer
#  project_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Partnership < ActiveRecord::Base
  belongs_to :user, foreign_key: :in_partner
  belongs_to :partner, foreign_key: :out_partner, class_name: "User"
end

app/models/passion_join.rb
# == Schema Information
#
# Table name: passion_joins
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  tag_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

class PassionJoin < ActiveRecord::Base
  belongs_to :tag
  belongs_to :user
end

app/models/pending_request.rb
# == Schema Information
#
# Table name: pending_requests
#
#  id                :integer          not null, primary key
#  in_user_id        :integer
#  out_user_id       :integer
#  in_user_accepted  :boolean          default(FALSE)
#  out_user_accepted :boolean          default(FALSE)
#  created_at        :datetime
#  updated_at        :datetime
#

class PendingRequest < ActiveRecord::Base
  
  belongs_to :in_user, class_name: "User"
  belongs_to :out_user, class_name: "User"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  public_description :text
#  user_id            :integer
#  status             :string(255)
#

class Project < ActiveRecord::Base
  validates :title, :description, presence: true
  belongs_to :user
  has_many :images
end

app/models/skill_join.rb
# == Schema Information
#
# Table name: skill_joins
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  tag_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

class SkillJoin < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  parent_id  :integer
#

class Tag < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :name, length: {maximum: 20}
  
  has_many :passion_joins, dependent: :destroy
  has_many :users_with_passion, through: :passion_joins, source: :users
  
  has_many :skill_joins, dependent: :destroy
  has_many :users_with_skill, through: :skill_joins, source: :users
  
  has_many :children, foreign_key: :parent_id, class_name: "Tag"
  belongs_to :parent, class_name: "Tag"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  interest        :text
#  created_at      :datetime
#  updated_at      :datetime
#  session_token   :string(255)
#  password_digest :string(255)
#  email           :string(255)
#  summary         :text
#  location        :string(255)
#  age             :integer
#  gender          :string(255)
#  lat             :float
#  long            :float
#  current_status  :string(255)
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token
  
  has_many :passion_joins
  has_many :passions, through: :passion_joins, source: :tag
  has_many :skill_joins
  has_many :skills, through: :skill_joins, source: :tag
  has_many :projects
  has_many :partnerships, foreign_key: :in_partner
  has_many :partners, through: :partnerships
  has_many :in_pending_requests, foreign_key: :in_user_id, class_name: "PendingRequest"
  has_many :out_pending_requests, foreign_key: :out_user_id, class_name: "PendingRequest"
  
  def password=(pt)
    @password = pt
    self.password_digest = BCrypt::Password.create(pt)
  end

  def is_password?(pt)
    BCrypt::Password.new(self.password_digest).is_password?(pt)
  end

  def self.find_by_credentials(params)
    
    user = User.find_by(email: params[:email].downcase)
    user.try(:is_password?, params[:password]) ? user :nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  def current_user
    session_token = session[:session_token]
    return nil if session_token.nil?
    User.find_by_session_token(session_token)
  end

  def login!
    @user.reset_session_token!
    session[:session_token] = @user.session_token
  end
  
  def require_login!
    redirect_to root_url unless current_user
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_access
    redirect_to static_pages_not_home_url unless session[:access_token] == "4vuZyBmDvbSi0JV54RuVug"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user_params[:email] = user_params[:email].downcase
    @user = User.find_by_credentials(user_params)
    if @user
      login!
      render json: @user
    else
      render json: ["Invalid Credentials"], status: 422
    end
  end
  
  def destroy
    @user = current_user
    logout!
    render json: @user
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_access, only: [:home]
  
  def home
  end
  
  def not_home
  end
  
  def allow_access
    if params[:password] == "Le@nSupp1y"
      session[:access_token] = "4vuZyBmDvbSi0JV54RuVug"
      redirect_to root_url
    else
      redirect_to static_pages_not_home_url
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/partnerships_helper.rb
module PartnershipsHelper
end

app/helpers/passion_joins_helper.rb
module PassionJoinsHelper
end

app/helpers/pending_requests_helper.rb
module PendingRequestsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skill_joins_helper.rb
module SkillJoinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="navbar-inner">
	  <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#explore-menu-collapse">
       <span class="sr-only"> Toggle Navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       </button>
	     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bridge-nav-collapse">
	       <span class="sr-only"> Toggle Navigation</span>
	       <span class="icon-bar"></span>
	       <span class="icon-bar"></span>
	       <span class="icon-bar"></span>
	       </button>
	 	     <a class="navbar-brand" href="#"><img src="/assets/brydge.jpg"></a>
	  </div>
		<div class="collapse navbar-collapse" id="explore-menu-collapse">
	  	<ul class="nav navbar-nav">
				<li ><a id="help" href="#help">Help</a></li>
				<li ><a id="sign-out" href="#">Log Out</a></li>
	    </ul>
		</div>
		<div class="navbar-collapse" id="bridge-nav-collapse">
	  	<ul class="nav navbar-nav navigation-holder">
					<li>
		   	 	 	<a id="explore" href="#explore"><i class="fa fa-globe fa-3x"></i><br>Explore</a>
			 		</li>
					<li>
		   	    <a id="create" href="#projects/new"><i class="fa fa-plus-square-o fa-3x"></i><br>Create</a>
				  </li>

					<li>
		     	  <a id="partners" href="#partnerships"><i class="fa fa-users fa-3x"></i><br>Partners</a>
					</li>
			
					<li>
		     	  <a id="projects" href="#projects"><i class="fa fa-sitemap fa-3x"></i> <br>Projects</a>
					</li>
			
					<li>
		     	  <a id="profile" href="#profile"><i class="fa fa-user fa-3x"></i><br>Profile</a>
					</li>
					
					<li>
						<a id="settings" href="#"><i class="fa fa-cog fa-3x"></i><br>Settings</a>
					</li>
	    </ul>
		</div>
	</div>
</nav>

app/views/static_pages/home.html.erb
<div id="content">
</div>

app/views/static_pages/not_home.html.erb
<form action="<%= static_pages_allow_access_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="password" name="password">
</form>